import React from 'react'

const ExperianTerms = () => {
  return (
    <>
     <main>
     <section class="container banner" style={{paddingTop:"2%",paddingBottom:"2%"}}>
      <div class="row">
        <div class="col-md-6">
      <h1 class="banner_title">
          <span class="text-cont" style={{color:"#3E2780"}}>EXPERIAN</span><br/>
            TERMS OF SERVICE
          </h1>
        </div>
        <div class="col-md-6 text-center">
        </div>
      </div>
    </section>
    
     <section class="container banner" style={{paddingTop:"2%",paddingBottom:"2%"}}>
      <div class="row">
      <h3 class="banner_title" style={{fontSize:"20px",color:"#858691"}}>
		
		<span style={{fontWeight:600}}>CONSENT IN RELATION TO ACCESS TO CREDIT INFORMATION THROUGH EXPERIAN</span><br/><br/>
		This End User Agreement (the “Agreement”) is made between you (the “User” or “You”) and Vibhuprada Services Pvt Ltd (herein reffered to as CreditHaat), a private limited company having its registered office at Office No. 10/11, 1st Floor, Tower B, Downtown City Vista, Survey Number 58/2, Fountain Road, Kharadi Pune. (“CreditHaat”, “Us” or “We”, which term shall include its successors and permitted assigns). The User and CreditHaat shall be collectively referred to as the “Parties” and individually as a “Party”.<br/><br/>
		You hereby consent to CreditHaat being appointed as your authorised representative to receive your Credit Information from Experian for the purpose of accessing credit worthiness and availing pre-approved offers (“End Use Purpose”).<br/><br/>
		BY EXECUTING THIS AGREEMENT / CONSENT FORM, YOU ARE EXPRESSLY AGREEING TO ACCESS THE EXPERIAN CREDIT INFORMATION REPORT AND CREDIT SCORE, AGGREGATE SCORES, INFERENCES, REFERENCES AND DETAILS (AS DEFINED BELOW) (TOGETHER REFERRED AS “CREDIT INFORMATION”). YOU HEREBY ALSO CONSENT TO SUCH CREDIT INFORMATION BEING PROVIDED BY EXPERIAN TO YOU AND CREDITHAAT BY USING EXPERIAN TOOLS, ALGORITHMS AND DEVICES AND YOU HEREBY AGREE, ACKNOWLEDGE AND ACCEPT THE TERMS AND CONDITIONS SET FORTH HEREIN.<br/><br/>
		
		<span style={{fontWeight:600}}>Terms and Conditions:</span><br/><br/>
		Information Collection, Use, Confidentiality, No-Disclosure and Data Purging<br/><br/>
		CreditHaat shall access your Credit Information as your authorized representative and CreditHaat shall use the Credit Information for limited End Use Purpose consisting of and in relation to the services proposed to be availed by you from CreditHaat. We shall not aggregate, retain, store, copy, reproduce, republish, upload, post, transmit, sell or rent the Credit Information to any other person and the same cannot be copied or reproduced other than as agreed herein and in furtherance to applicable law including the CICRA.<br/><br/>
		The Parties agree to protect and keep confidential the Credit Information both online and offline.<br/><br/>
		The Credit Information shared by you, or received on by us on your behalf shall be destroyed, purged, erased immediately upon the completion of the transaction/ End Use Purpose for which the Credit Information report was procured, this period not being longer than 6 months.<br/><br/>
		
		<span  style={{fontWeight:600}}>Governing Law and Jurisdiction</span><br/><br/>
		The relationship between you and CreditHaat shall be governed by laws of India and all claims or disputes arising there from shall be subject to the exclusive jurisdiction of the courts of Mumbai.<br/><br/>

		<span  style={{fontWeight:600}}>Definitions:</span><br/><br/>
        Capitalised terms used herein but not defined above shall have the following meanings: <br/><br/>
		
		<span  style={{fontWeight:600}}>Business Day</span><br/><br/>
        means a day (other than a public holiday) on which banks are open for general business in Mumbai.<br/><br/>
		
		<span  style={{fontWeight:600}}>Credit Information Report</span><br/><br/>
		means the credit information / scores/ aggregates / variables / inferences or reports which shall be generated by Experian<br/><br/>
		
		<span  style={{fontWeight:600}}>Credit Score</span><br/><br/>
		means the score which shall be mentioned on the Credit Information Report which shall be computed by Experian<br/><br/>
		
		<span  style={{fontWeight:600}}>CICRA</span>
		shall mean the Credit Information Companies (Regulation) Act, 2005 read with the Credit Information Companies Rules, 2006 and the Credit Information Companies Regulations, 2006, and shall include any other rules and regulations prescribed thereunder.<br/><br/>
		
		<span  style={{fontWeight:600}}>PLEASE READ THE ABOVEMENTIONED TERMS AND CONDITIONS AND CLICK ON “ACCEPT” FOLLOWED BY THE LINK BELOW TO COMPLETE THE AUTHORISATION PROCESS/  FOR SHARING OF YOUR CREDIT INFORMATION BY EXPERIAN WITH CreditHaat IN ITS CAPACITY AS YOUR AUTHORISED REPRESENTATIVE.</span><br/><br/>

		<span  style={{fontWeight:600}}>BY CLICKING “ACCEPT” YOU AGREE AND ACCEPT THE DISCLAIMERS AND TERMS AND CONDITIONS SET OUT HEREIN.</span><br/><br/>

		<br/><br/>
		** This document is an electronic record in terms of the Information Technology Act, 2000 and Rules made there under, and the amended provisions pertaining to electronic records.    
          </h3>
      </div>
    </section>    
  </main>
    </>
  )
}

export default ExperianTerms